services:
  fullstack_client:
    container_name: fullstack_client
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "5173:5173"
    volumes:
      - ./src:/src
    networks:
      - project_network

networks:
  project_network:
