include:
  - ../server/docker-compose-db.yml
  - ../server/docker-compose-server.yml
  - ./docker-compose-client.yml

services:
  client_e2e_test:
    container_name: client_e2e_test
    tty: true
    build: 
      context: .
      dockerfile: Dockerfile.e2e
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: ./src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./cypress
          target: ./cypress
          ignore:
            - node_modules/
        - action: rebuild
          path: ../server/src
          target: ../server/src
          ignore:
            - node_modules/
    depends_on:
      db_migrate:
          condition: service_completed_successfully
      fullstack_client:
          condition: service_healthy
    volumes:
      - ./cypress:/cypress
      - /cypress.config.ts:/cypress.config.ts
    networks:
      - project_network

networks:
  project_network:
