stages:
  - setup
  - lint
  - test
  - test-coverage
  # - e2e

setup:
  stage: setup
  image: node:22.12.0
  cache:
    paths:
      - './**/node_modules/'
  script:
    - npm run install-everything
  artifacts:
    expire_in: 1 days
    paths:
      - './**/node_modules/'
    when: on_success

eslint:
  stage: lint
  image: node:22.12.0
  script:
    - npm run lint
  only:
    - merge_requests
    - branches

test_coverage_client:
  stage: test-coverage
  image: node:22.12.0
  script:
    - cd client
    - npm run test:ci
  coverage: '/All\sfiles.*?\s+(\d+.\d+)/'

test_coverage_server:
  stage: test-coverage
  image: node:22.12.0
  script:
    - cd server
    - npm run test:ci
  coverage: '/All\sfiles.*?\s+(\d+.\d+)/'

client-test:
  stage: test
  image: node:22.12.0
  script:
    - cd client
    - npm run test

server-test:
  stage: test
  image: node:22.12.0
  script:
    - cd server
    - npm run test

# Step 4: client End-to-End Tests with Maestro
# client-e2e-maestro:
#   stage: e2e
#   image: maestroqa/maestro-cli:latest
#   before_script:
#     - mkdir -p maestro-artifacts
#     - export ANDROID_HOME=/sdk/android
#   script:
#     - maestro test mobile/maestro/register_test.yaml --output maestro-artifacts
#   artifacts:
#     paths:
#       - maestro-artifacts/
#     when: always

# Step 5: server End-to-End Tests with Cypress
# server-e2e-cypress:
#   stage: e2e
#   image: cypress/included:12.6.0
#   script:
#     - cypress run --config-file cypress.json
#   artifacts:
#     paths:
#       - cypress/results/
#     when: always
