stages:
  - setup
  - test
  # - lint
  # - e2e

setup:
  stage: setup
  image: node:22.12.0
  script:
    - cd cilent
    - npm install
    - cd ../server
    - npm install
    - cd ../webscraping
    - npm install
    - cd ..
  artifacts:
    paths:
      - server/
      - cilent/
      - webscraping/
    when: on_success

cilent-test:
  stage: test
  image: node:22.12.0
  script:
    - cd cilent
    - npm run test

server-test:
  stage: test
  image: node:22.12.0
  script:
    - cd server
    - npm run test

# eslint:
#   stage: lint
#   image: node:22.12.0
#   before_script:
#     - npm install
#   script:
#     - npm run lint
#   only:
#     - merge_requests
#     - branches

# Step 4: cilent End-to-End Tests with Maestro
# cilent-e2e-maestro:
#   stage: e2e
#   image: maestroqa/maestro-cli:latest
#   before_script:
#     - mkdir -p maestro-artifacts
#     - export ANDROID_HOME=/sdk/android
#   script:
#     - maestro test mobile/maestro/register_test.yaml --output maestro-artifacts
#   artifacts:
#     paths:
#       - maestro-artifacts/
#     when: always

# Step 5: server End-to-End Tests with Cypress
# server-e2e-cypress:
#   stage: e2e
#   image: cypress/included:12.6.0
#   script:
#     - cypress run --config-file cypress.json
#   artifacts:
#     paths:
#       - cypress/results/
#     when: always
