services:
  fullstack_server:
    container_name: fullstack_server
    tty: true
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./server/src:/server/src
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./server/.env
    networks:
      - project_network

volumes:
  cosc680-db:

networks:
  project_network:
