services:
  fullstack_client:
    container_name: fullstack_client
    tty: true
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./client/.env
    ports:
      - "5173:5173"
    volumes:
      - ./client/src:/client/src
    networks:
      - project_network

networks:
  project_network:
