services:
  fullstack_server:
    container_name: fullstack_server
    # depends_on:
    #   fullstack_db:
    #     condition: service_healthy
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./server/src:/server/src
    # healthcheck:
    #     test: [ "CMD", "curl", "--fail", "-G", "http://localhost:${PORT}" ]
    #     interval: 30s
    #     timeout: 10s
    #     retries: 30
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./server/.env
    networks:
      - project_network

volumes:
  cosc680-db:

networks:
  project_network:
