version: '3.8'
services:
  postgres:
    image: postgres:17.2
    container_name: postgres_dev
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432" # Expose PostgreSQL on localhost:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist PostgreSQL data

  express:
    build:
      context: ./backend
      dockerfile: Dockerfile # Dockerfile for the Express.js app
    container_name: express_app
    environment:
      DB_HOST: postgres
      DB_USER: dev_user
      DB_PASSWORD: dev_password
      DB_NAME: dev_db
      DB_PORT: 5432
    ports:
      - "3000:3000" # Expose Express.js on localhost:3000
    depends_on:
      - postgres # Ensure PostgreSQL starts before Express.js

volumes:
  postgres_data:

