services:
  fullstack_db:
    container_name: fullstack_db
    image: postgres:17.2
    tty: true
    restart: always
    env_file:
      - ./server/.env
    volumes:
      - cosc680-db:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - project_network

  db_migrate:
    container_name: db_migrate
    tty: true
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    command: sh -c "npm run db:generate && npm run db:push"
    volumes:
      - ./server/src:/server/src
    networks:
      - project_network

volumes:
  cosc680-db:

networks:
  project_network:
