services:
  db:
    container_name: db
    image: postgres:17.2
    tty: true
    restart: always
    env_file:
      - ./.env
    volumes:
      - cosc680-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - project_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  cosc680-db:

networks:
  project_network:
