services:
  fullstack_server:
    container_name: fullstack_server
    tty: true
    develop:
      watch:
        - action: rebuild
          path: .
          target: .
          ignore:
            - node_modules/
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/src
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    networks:
      - project_network

volumes:
  cosc680-db:

networks:
  project_network:
