services:
  db:
    container_name: db
    image: postgres:17.2
    tty: true
    restart: always
    env_file:
      - ./.env
    volumes:
      - cosc680-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - project_network

  db_migrate:
    container_name: db_migrate
    tty: true
    # command: sh -c 'npm run db:reset && npm run db:generate && npm run db:push && npm run db:seed'
    command: sh -c 'npm run db:generate && npm run db:push && npm run db:seed'
    develop:
      watch:
        - action: rebuild
          path: ./src/db
          target: ./src/db
          ignore:
            - node_modules/
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    networks:
      - project_network

volumes:
  cosc680-db:

networks:
  project_network:
