services:
  server:
    container_name: server
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: ./src
          ignore:
            - node_modules/
    volumes:
      - ./src:/src
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    networks:
      - project_network

volumes:
  cosc680-db:

networks:
  project_network:
