include:
  - ./docker-compose-db.yml

services:
  test_fullstack_server:
    container_name: test_fullstack_server
    tty: true
    develop:
      watch:
        - action: rebuild
          path: .
          target: .
          ignore:
            - node_modules/
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    command: sh -c "npm run tests"
    volumes:
      - ./src:/src
    networks:
      - project_network

volumes:
  cosc680-db:

networks:
  project_network:
